config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  resources :products
  resources :transportations
  resources :customers
  resources :suppliers
  resources :purchases
  resources :location_in_warehouses
  resources :families
  resources :brands
  devise_for :users

  get 'welcome/contacts'
  get 'welcome/productos'
  get 'welcome/proveedores'
  get 'welcome/compras'
  get 'welcome/ventas'
  get 'welcome/pedidos'
  get 'welcome/clientes'

  get 'welcome/reportes'

  root 'welcome#index'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/family.rb
class Family < ActiveRecord::Base
end

app/models/location_in_warehouse.rb
class LocationInWarehouse < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :foto1, styles: { small: "200x200", medium: "600x600>", large: "800x800>" }, default_url: ""
  validates_attachment_content_type :foto1, content_type: /\Aimage\/.*\z/

  has_attached_file :foto2, styles: { small: "200x200", medium: "600x600>", large: "800x800>" }, default_url: ""
  validates_attachment_content_type :foto2, content_type: /\Aimage\/.*\z/

  has_attached_file :foto3, styles: { small: "200x200", medium: "600x600>", large: "800x800>" }, default_url: ""
  validates_attachment_content_type :foto3, content_type: /\Aimage\/.*\z/

  has_attached_file :foto4, styles: { small: "200x200", medium: "600x600>", large: "800x800>" }, default_url: ""
  validates_attachment_content_type :foto4, content_type: /\Aimage\/.*\z/
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  has_attached_file :factura, styles: { small: "50x50", medium: "400x400>", large: "800x800>" }, default_url: ""
  validates_attachment_content_type :factura, content_type: /\Aimage\/.*\z/
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/transportation.rb
class Transportation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
    @brand = Brand.new
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to action: 'index' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to action: 'index' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:brand)
    end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_family, only: [:show, :edit, :update, :destroy]

  # GET /families
  # GET /families.json
  def index
    @families = Family.all
    @family = Family.new
  end

  # GET /families/1
  # GET /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families
  # POST /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to action: 'index' }
        format.json { render :show, status: :created, location: @family }
      else
        format.html { render :new }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1
  # PATCH/PUT /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to action: 'index' }
        format.json { render :show, status: :ok, location: @family }
      else
        format.html { render :edit }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.json
  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_url, notice: 'Family was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_params
      params.require(:family).permit(:family)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @contacts = Contact.all
    @contact = Contact.new
  end

  def productos
    @products = Product.all
    @product = Product.new
    @brands = Brand.all
    @brand = Brand.new
  end

  def proveedores
    @suppliers = Supplier.all
    @supplier = Supplier.new
  end

  def compras
    @purchases = Purchase.all
    @purchase = Purchase.new
  end

  def clientes
    @customers = Customer.all
    @customer = Customer.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/transportations_helper.rb
module TransportationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/families/_form.html.erb
<%= form_for(@family, remote: true) do |f| %>
  <% if @family.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@family.errors.count, "error") %> prohibited this family from being saved:</h2>

      <ul>
      <% @family.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xs-7 col-md-9 col-lg-10">
      <%= f.text_field :family, :class => 'input-shaptar', :placeholder => 'Ingresar Familia' %>
    </div>
    <div class="col-xs-5 col-md-3 col-lg-2">
      <%= f.submit 'Guardar', :class => 'button-shaptar-green' %>
    </div>
  </div>

<% end %>

app/views/families/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Editar Familia</h1>
  </div>
</div>

<%= render 'form' %>

<%= link_to 'No hacer cambios', families_path %>

app/views/families/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Ingresar Familias</h1>
  </div>
</div>

<%= render 'form' %>

<div class="row">
  <div class="col-xs-12">
    <table>
      <thead>
        <tr>
          <th>Familias</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @families.each do |family| %>
          <tr>
            <td><%= family.family %></td>
            <td class="text-end"><%= link_to 'Editar', edit_family_path(family) %> | <%= link_to 'Eliminar', family, method: :delete, data: { confirm: 'Está seguro de eliminar esta familia?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/families/new.html.erb
<h1>New Family</h1>

<%= render 'form' %>

<%= link_to 'Back', families_path %>

app/views/families/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Family:</strong>
  <%= @family.family %>
</p>

<%= link_to 'Edit', edit_family_path(@family) %> |
<%= link_to 'Back', families_path %>