config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  resources :products
  resources :transportations
  resources :customers
  resources :suppliers
  resources :purchases
  resources :location_in_warehouses
  resources :families
  resources :brands
  devise_for :users

  get 'welcome/contacts'
  get 'welcome/productos'
  get 'welcome/proveedores'
  get 'welcome/compras'
  get 'welcome/ventas'
  get 'welcome/pedidos'
  get 'welcome/clientes'

  get 'welcome/reportes'

  root 'welcome#index'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/family.rb
class Family < ActiveRecord::Base
end

app/models/location_in_warehouse.rb
class LocationInWarehouse < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :foto1, styles: { small: "200x200", medium: "600x600>", large: "800x800>" }, default_url: ""
  validates_attachment_content_type :foto1, content_type: /\Aimage\/.*\z/

  has_attached_file :foto2, styles: { small: "200x200", medium: "600x600>", large: "800x800>" }, default_url: ""
  validates_attachment_content_type :foto2, content_type: /\Aimage\/.*\z/

  has_attached_file :foto3, styles: { small: "200x200", medium: "600x600>", large: "800x800>" }, default_url: ""
  validates_attachment_content_type :foto3, content_type: /\Aimage\/.*\z/

  has_attached_file :foto4, styles: { small: "200x200", medium: "600x600>", large: "800x800>" }, default_url: ""
  validates_attachment_content_type :foto4, content_type: /\Aimage\/.*\z/
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  has_attached_file :factura, styles: { small: "50x50", medium: "400x400>", large: "800x800>" }, default_url: ""
  validates_attachment_content_type :factura, content_type: /\Aimage\/.*\z/
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/transportation.rb
class Transportation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
    @brand = Brand.new
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to action: 'index' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to action: 'index' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:brand)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @contacts = Contact.all
    @contact = Contact.new
  end

  def productos
    @products = Product.all
    @product = Product.new
    @brands = Brand.all
    @brand = Brand.new
  end

  def proveedores
    @suppliers = Supplier.all
    @supplier = Supplier.new
  end

  def compras
    @purchases = Purchase.all
    @purchase = Purchase.new
  end

  def clientes
    @customers = Customer.all
    @customer = Customer.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/transportations_helper.rb
module TransportationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/clientes.html.erb
<% if user_signed_in? %>

<!-- Nav tabs -->

<div class="row">
  <div class="col-xs-12">
    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#clientes" role="tab">Clientes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#nuevo-cliente" role="tab">Nuevo</a>
      </li>
    </ul>
  </div>
</div>

<!-- Tab panes -->

<div class="tab-content">

  <div class="tab-pane active" id="clientes" role="tabpanel">
    <div class="row">
      <div class="col-xs-8 col-md-10">
        <input type="text" class="input-shaptar" placeholder="Ingresar Código">
      </div>
      <div class="col-xs-4 col-md-2">
        <button type="button" class="button-shaptar-green">Buscar</button>
      </div>

      <div class="col-xs-12 negative">
        <pre>
          <table>

            <tr>
              <th></th>
              <th></th>
              <th>Id</th>
              <th>Código</th>
              <th>Nit</th>
              <th>Nombre Cliente</th>
              <th>Razón Social</th>
              <th>País</th>
              <th>Departamento o Estado</th>
              <th>Dirección</th>
              <th>Teléfono 1</th>
              <th>Teléfono 2</th>
              <th>Celular 1</th>
              <th>Celular 2</th>
              <th>Correo Electrónico</th>
              <th>Página Web</th>
              <th>Transporte</th>
              <th>Crédito en quetzales</th>
              <th>Porcentaje en Descuento</th>
              <th>Observaciones</th>
            </tr>

            <% @customers.each do |customer| %>
            <tr>
              <td><%= link_to 'Editar', edit_customer_path(customer) %></td>
              <td><%= link_to 'Eliminar', customer, method: :delete, data: { confirm: 'Esta seguro de eliminar este Cliente?' } %></td>
              <td><%= customer.id %></td>
              <td><%= customer.customer_code %></td>
              <td><%= customer.nit %></td>
              <td><%= customer.customer_name %></td>
              <td><%= customer.company_name %></td>
              <td><%= customer.country %></td>
              <td><%= customer.department_or_state %></td>
              <td><%= customer.address %></td>
              <td><%= customer.telephone_1 %></td>
              <td><%= customer.telephone_2 %></td>
              <td><%= customer.mobile_1 %></td>
              <td><%= customer.mobile_2 %></td>
              <td><%= customer.email %></td>
              <td><%= customer.web_page %></td>
              <td><%= customer.transportation %></td>
              <td><%= customer.credit_in_quetzales %></td>
              <td><%= customer.discount_percentage %></td>
              <td><%= customer.observations %></td>
            </tr>
            <% end %>

          </table>
        </pre>
      </div>
    </div>
  </div>

  <div class="tab-pane" id="nuevo-cliente" role="tabpanel">
    <br><h2 class="form">Ingresar un Nuevo Cliente</h2>
    <%= render 'customers/form' %>
  </div>

</div>

<% else %>

<% end %>

app/views/welcome/compras.html.erb
<% if user_signed_in? %>

<!-- Nav tabs -->

<div class="row">
  <div class="col-xs-12">
    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#compras" role="tab">Compras</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#nueva-compra" role="tab">Nueva</a>
      </li>
    </ul>
  </div>
</div>

<!-- Tab panes -->

<div class="tab-content">

  <div class="tab-pane active" id="compras" role="tabpanel">
    <div class="row">
      <div class="col-xs-8 col-md-10">
        <input type="text" class="input-shaptar" placeholder="Ingresar Código">
      </div>
      <div class="col-xs-4 col-md-2">
        <button type="button" class="button-shaptar-green">Buscar</button>
      </div>

      <div class="col-xs-12 negative">
        <pre>
          <table>

            <tr>
              <th></th>
              <th></th>
              <th></th>
              <th>Id</th>
              <th>Proveedor</th>
              <th>Factura Serie</th>
              <th>Factura Número</th>
              <th>Fecha de Compra</th>
              <th>Total de la Compra</th>
              <th>Observaciones</th>
            </tr>

            <% @purchases.each do |purchase| %>
            <tr>
              <td><%= link_to 'Editar', edit_purchase_path(purchase) %></td>
              <td><%= link_to 'Ver', purchase %></td>
              <td><%= link_to 'Eliminar', purchase, method: :delete, data: { confirm: 'Esta seguro de eliminar esta Compra' } %></td>
              <td><%= purchase.id %></td>
              <td><%= purchase.supplier_code %></td>
              <td><%= purchase.invoice_series %></td>
              <td><%= purchase.invoice_number %></td>
              <td><%= purchase.purchase_date %></td>
              <td><%= purchase.total_purchase %></td>
              <td><%= purchase.observations %></td>
            </tr>
            <% end %>

          </table>
        </pre>
      </div>
    </div>
  </div>

  <div class="tab-pane" id="nueva-compra" role="tabpanel">
    <br><h2 class="form">Ingresar una Nueva Compra</h2>
    <%= render 'purchases/form' %>
  </div>

</div>

<% else %>

<% end %>

app/views/welcome/contacts.html.erb
<br><br><br><br><br><br><br><br><br><br><br>
<center><h1><b>GRACIAS POR ESCRIBIRNOS</b></h1></center>
<center><h2>En breve nos estaremos comunicando con usted</h2></center>

app/views/welcome/index.html.erb
<% if user_signed_in? %>

<div class="row">

  <div class="col-xs-12 col-lg-4">
    <div class="box-logo-white"><%= image_tag "logo-macar.png" %></div>
  </div>

  <div class="col-xs-12 col-lg-4 box-perfil">
    <h4><b>Información General</b></h4>

    <b>Representante Legal:</b>
    <p><%= current_user.legal_representative %></p>

    <b>Nit:</b>
    <p><%= current_user.nit %></p>

    <b>Nombre de la Empresa:</b>
    <p><%= current_user.company_name %></p>

    <b>Razón Social:</b>
    <p><%= current_user.business_name %></p>
  </div>
  <div class="col-xs-12 col-lg-4 box-perfil">
    <h4><b>Información de Contacto</b></h4>

    <b>Teléfono:</b>
    <p><%= current_user.phone %></p>

    <b>Correo Electrónico</b>
    <p><%= current_user.email %></p>

    <b>Dirección de la Empresa</b>
    <p><%= current_user.company_address %></p>
  </div>

</div>

<div class="col-xs-3 col-sm-3 col-md-2 col-lg-1">
  <div class="box-editar-perfil">
    <div class="informacion"><%= link_to image_tag("informacion.svg"), edit_user_registration_path %></div>
    <div class="foto"><%= image_tag "foto.svg" %></div>
  </div>
</div>

<% else %>

<div class="box-landing-page-background">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-lg-4 box-logo-black">
      <%= image_tag "logo-macar.png" %>
    </div>
  </div>
</div>

<div class="box-landing-page">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="text-center">Quienes Somos?</h1>
      <br>
      <p>
        Somos una empresa guatemalteca, dedicada a la importación de productos
        tecnológicos para cubrir las necesidades de nuestros clientes y
        colaboradores, se fundamenta en los principios de honestidad, honradez y
        respeto, contamos con el respaldo de un equipo colaborador de amplia y
        diversa experiencia en la venta de productos y servicios de tecnología.
      </p>
      <br>
      <h3>Misión</h3>
      <p>
        Ser una empresa exitosa, comprometida con el desarrollo y la excelencia
        en el mercado de la tecnología, velar por la satisfacción de nuestros
        clientes con productos de alta calidad y excelente servicio por parte de
        nuestros colaboradores.
      </p>
      <h3>Visión</h3>
      <p>
        Crecer de la mano de nuestros clientes, brindandoles el mejor servicio,
        la mejor calidad en nuestros productos. Lograr posicionar nuestras
        marcas y superar las existentes en el mercado, para que nuestros
        clientes confíen y cuenten con nosotros y de esta manera lograr la
        expansión a nivel centroamericano.
      </p>
    </div>
    <div class="col-xs-12">
      <h1></h1>
    </div>
  </div>
</div>

<div class="box-landing-page-gray">
  <div class="row">
    <div class="col-xs-12 text-center">
      <h1>Nuestros Productos</h1>
    </div>
    <div class="col-xs-12">
      <h1></h1>
    </div>
  </div>
</div>

<div class="box-landing-page">
  <div class="row">
    <div class="col-xs-12 text-center">
      <h1>Ofertas Especiales</h1>
    </div>
    <div class="col-xs-12">
      <h1></h1>
    </div>
  </div>
</div>

<div class="box-landing-page-gray">
  <div class="row">

    <div class="col-xs-12 text-center">
      <h1>Marcas de Confianza</h1>
      <h4>Algunas de las marcas en las que somos distribuidor autorizado</h4>
    </div>

    <div class="col-xs-12 col-sm-6 col-lg-4">
      <div class="box-logo-white"><%= image_tag "logo-benssini.png", width: '85%' %></div>
    </div>

    <div class="col-xs-12 col-sm-6 col-lg-4">
      <div class="box-logo-white"><%= image_tag "logo-trek.png", width: '90%' %></div>
    </div>

    <div class="col-xs-12 col-sm-6 col-lg-4">
      <div class="box-logo-white"><%= image_tag "logo-scanbrik.png", width: '90%' %></div>
    </div>

    <div class="col-xs-12 col-sm-6 col-lg-4">
      <div class="box-logo-white"><%= image_tag "logo-miyakousa.png", width: '90%' %></div>
    </div>

    <div class="col-xs-12 col-sm-6 col-lg-4">
      <div class="box-logo-white"><%= image_tag "logo-wahl.png", width: '90%' %></div>
    </div>

    <div class="col-xs-12 col-sm-6 col-lg-4">
      <div class="box-logo-white"><%= image_tag "logo-macar-best-of-the-best.png", width: '90%' %></div>
    </div>

  </div>
</div>

<div class="box-landing-page">
  <%= render 'contacts/form' %>
</div>

<% end %>

app/views/welcome/pedidos.html.erb
<% if user_signed_in? %>

<!-- Nav tabs -->
<div class="row">
  <div class="col-xs-12">
    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#pedidos" role="tab">Pedidos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#ingresar-nuevo-pedido" role="tab">Ingresar Nuevo Pedido</a>
      </li>
    </ul>
  </div>
</div>

<!-- Tab panes -->
<div class="tab-content">

  <div class="tab-pane active" id="pedidos" role="tabpanel">
    <div class="row">
      <div class="col-xs-8 col-md-10">
        <input type="text" class="input-shaptar" placeholder="Ingresar Código">
      </div>
      <div class="col-xs-4 col-md-2">
        <button type="button" class="button-shaptar-green">Buscar</button>
      </div>
    </div>
  </div>

  <div class="tab-pane" id="ingresar-nuevo-pedido" role="tabpanel">
    <div class="row">
      <div class="col-xs-10">
        <input type="text" class="input-shaptar" placeholder="Ingresar Código">
      </div>
      <div class="col-xs-2">
        <button type="button" class="button-shaptar-green">Buscar</button>
      </div>
    </div>
  </div>

</div>

<% else %>

<% end %>

app/views/welcome/productos.html.erb
<% if user_signed_in? %>

<!-- Nav tabs -->

<div class="row">
  <div class="col-xs-12">
    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#productos-activos" role="tab">Productos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#nuevos-productos" role="tab">Nuevo</a>
      </li>
    </ul>
  </div>
</div>

<!-- Tab panes -->

<div class="tab-content">

  <div class="tab-pane active" id="productos-activos" role="tabpanel">
    <div class="row">
      <div class="col-xs-8 col-md-10">
        <input type="text" class="input-shaptar" placeholder="Ingresar Código">
      </div>
      <div class="col-xs-4 col-md-2">
        <button type="button" class="button-shaptar-green">Buscar</button>
      </div>

      <div class="col-xs-12 negative">
        <pre>
          <table>

            <tr>
              <th></th>
              <th></th>
              <th></th>
              <th>Id</th>
              <th>Código</th>
              <th>Código de Barras</th>
              <th>Nombre del Producto</th>
              <th>Descripción</th>
              <th>Fecha de Compra</th>
              <th>Costo en Quetzales</th>
              <th>Precio de Venta</th>
              <th>Porcentaje de Descuento</th>
              <th>Stock</th>
              <th>Proveedor</th>
              <th>Marca</th>
              <th>Familia</th>
              <th>Ubicación en Bodega</th>
            </tr>

            <% @products.each do |product| %>
            <tr>
              <td><%= link_to 'Editar', edit_product_path(product) %></td>
              <td><%= link_to 'Ver', product %></td>
              <td><%= link_to 'Eliminar', product, method: :delete, data: { confirm: 'Está seguro de eliminar este producto?' } %></td>
              <td><%= product.id %></td>
              <td><%= product.product_code %></td>
              <td><%= product.barcode %></td>
              <td><%= product.product_name %></td>
              <td><%= product.description %></td>
              <td><%= product.purchase_date %></td>
              <td>Q <%= product.cost_in_quetzales %></td>
              <td>Q <%= product.sale_price %></td>
              <td><%= product.percentage_in_sale %> % </td>
              <td><%= product.number_of_articles %></td>
              <td><%= product.name_supplier %></td>
              <td><%= product.name_brand %></td>
              <td><%= product.name_family %></td>
              <td><%= product.name_location_in_warehouse %></td>
            </tr>
            <% end %>

          </table>
        </pre>
      </div>
    </div>
  </div>

  <div class="tab-pane" id="nuevos-productos" role="tabpanel">
    <br><h2 class="form">Ingresar un Nuevo Producto</h2>
    <%= render 'products/form' %>
  </div>

</div>

<% else %>

<% end %>

app/views/welcome/proveedores.html.erb
<% if user_signed_in? %>

<!-- Nav tabs -->

<div class="row">
  <div class="col-xs-12">
    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#proveedores" role="tab">Proveedores</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#nuevo-proveedor" role="tab">Nuevo</a>
      </li>
    </ul>
  </div>
</div>

<!-- Tab panes -->

<div class="tab-content">

  <div class="tab-pane active" id="proveedores" role="tabpanel">
    <div class="row">
      <div class="col-xs-8 col-md-10">
        <input type="text" class="input-shaptar" placeholder="Ingresar Código">
      </div>
      <div class="col-xs-4 col-md-2">
        <button type="button" class="button-shaptar-green">Buscar</button>
      </div>

      <div class="col-xs-12 negative">
        <pre>
          <table>

            <tr>
              <th></th>
              <th></th>
              <th>Id</th>
              <th>Código</th>
              <th>Nit</th>
              <th>Nombre del Proveedor</th>
              <th>Razón Social</th>
              <th>País</th>
              <th>Departamento o Estado</th>
              <th>Dirección</th>
              <th>teléfono 1</th>
              <th>teléfono 2</th>
              <th>Celular 1</th>
              <th>Celular 2</th>
              <th>Correo Electrónico</th>
              <th>Página Web</th>
              <th>Observaciones</th>
            </tr>

            <% @suppliers.each do |supplier| %>
            <tr>
              <td><%= link_to 'Editar', edit_supplier_path(supplier) %></td>
              <td><%= link_to 'Eliminar', supplier, method: :delete, data: { confirm: 'Esta seguro de eliminar este proveedor?' } %></td>
              <td><%= supplier.id %></td>
              <td><%= supplier.supplier_code %></td>
              <td><%= supplier.nit %></td>
              <td><%= supplier.supplier_name %></td>
              <td><%= supplier.company_name %></td>
              <td><%= supplier.country %></td>
              <td><%= supplier.department_or_state %></td>
              <td><%= supplier.full_address %></td>
              <td><%= supplier.telephone_1 %></td>
              <td><%= supplier.telephone_2 %></td>
              <td><%= supplier.mobile_1 %></td>
              <td><%= supplier.mobile_2 %></td>
              <td><%= supplier.email %></td>
              <td><%= supplier.web_page %></td>
              <td><%= supplier.observations %></td>
            </tr>
            <% end %>

          </table>
        </pre>
      </div>
    </div>
  </div>

  <div class="tab-pane" id="nuevo-proveedor" role="tabpanel">
    <br><h2 class="form">Ingresar un Nuevo Proveedor</h2>
    <%= render 'suppliers/form' %>
  </div>

</div>

<% else %>

<% end %>

app/views/welcome/reportes.html.erb
<% if user_signed_in? %>

<!-- Nav tabs -->
<div class="row">
  <div class="col-xs-12">
    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle active" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Reportes</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">Ventas</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Envios</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Compras</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Devoluciones</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Artículos</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Clientes</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Cuentas por Cobrar</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Proveedores</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Vendedores</a>
        </div>
      </li>
    </ul>
  </div>
</div>

<!-- Tab panes -->
<div class="tab-content">

  <div class="tab-pane active" id="facturar" role="tabpanel">
    <div class="row">
      <div class="col-xs-10">
        <input type="text" class="input-shaptar" placeholder="Ingresar Código">
      </div>
      <div class="col-xs-2">
        <button type="button" class="button-shaptar-green">Buscar</button>
      </div>
    </div>
  </div>

  <div class="tab-pane" id="envios" role="tabpanel">
    <div class="row">
      <div class="col-xs-10">
        <input type="text" class="input-shaptar" placeholder="Ingresar Código">
      </div>
      <div class="col-xs-2">
        <button type="button" class="button-shaptar-green">Buscar</button>
      </div>
    </div>
  </div>

</div>

<% else %>

<% end %>