config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  resources :products
  resources :transportations
  resources :customers
  resources :suppliers
  resources :purchases
  resources :location_in_warehouses
  resources :families
  resources :brands
  devise_for :users

  get 'welcome/contacts'
  get 'welcome/productos'
  get 'welcome/proveedores'
  get 'welcome/compras'
  get 'welcome/ventas'
  get 'welcome/pedidos'
  get 'welcome/clientes'

  get 'welcome/reportes'

  root 'welcome#index'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/family.rb
class Family < ActiveRecord::Base
end

app/models/location_in_warehouse.rb
class LocationInWarehouse < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :foto1, styles: { small: "200x200", medium: "600x600>", large: "800x800>" }, default_url: ""
  validates_attachment_content_type :foto1, content_type: /\Aimage\/.*\z/

  has_attached_file :foto2, styles: { small: "200x200", medium: "600x600>", large: "800x800>" }, default_url: ""
  validates_attachment_content_type :foto2, content_type: /\Aimage\/.*\z/

  has_attached_file :foto3, styles: { small: "200x200", medium: "600x600>", large: "800x800>" }, default_url: ""
  validates_attachment_content_type :foto3, content_type: /\Aimage\/.*\z/

  has_attached_file :foto4, styles: { small: "200x200", medium: "600x600>", large: "800x800>" }, default_url: ""
  validates_attachment_content_type :foto4, content_type: /\Aimage\/.*\z/
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  has_attached_file :factura, styles: { small: "50x50", medium: "400x400>", large: "800x800>" }, default_url: ""
  validates_attachment_content_type :factura, content_type: /\Aimage\/.*\z/
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/transportation.rb
class Transportation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
    @brand = Brand.new
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to action: 'index' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to action: 'index' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:brand)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to controller: 'welcome', action: 'contacts' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :telephone, :email, :message)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @contacts = Contact.all
    @contact = Contact.new
  end

  def productos
    @products = Product.all
    @product = Product.new
    @brands = Brand.all
    @brand = Brand.new
  end

  def proveedores
    @suppliers = Supplier.all
    @supplier = Supplier.new
  end

  def compras
    @purchases = Purchase.all
    @purchase = Purchase.new
  end

  def clientes
    @customers = Customer.all
    @customer = Customer.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/transportations_helper.rb
module TransportationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/brands/_form.html.erb
<%= form_for(@brand, remote: true) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
        <% @brand.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>

  <% end %>

  <div class="row">
    <div class="col-xs-7 col-md-9 col-lg-10">
      <%= f.text_field :brand, :class => 'input-shaptar', :placeholder => 'Ingresar Marca' %>
    </div>
    <div class="col-xs-5 col-md-3 col-lg-2">
      <%= f.submit 'Guardar', :class => 'button-shaptar-green' %>
    </div>
  </div>

<% end %>

app/views/brands/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Editar Marcas</h1>
  </div>
</div>

<%= render 'form' %>

<%= link_to 'No hacer cambios', brands_path %>

app/views/brands/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Ingresar Marcas</h1>
  </div>
</div>

<%= render 'form' %>

<div class="row">
  <div class="col-xs-12">
    <table>
      <thead>
        <tr>
          <th>Marcas</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @brands.each do |brand| %>
          <tr>
            <td><%= brand.brand %></td>
            <td class="text-end"><%= link_to 'Editar', edit_brand_path(brand) %> | <%= link_to 'Eliminar', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @brand.brand %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

    <div class="col-xs-12 text-center">
      <h1>Contactenos</h1>
      <h4>Escríbanos si desea más información sobre nuestra gama de productos</h4>
    </div>

    <div class="col-xs-12 col-md-6">
      <div class="row">
        <div class="col-xs-12">
          <%= f.text_area :message, :class => 'textarea-contacto-shaptar', :placeholder => 'Escriba su Mensaje:' %>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-md-6">
      <div class="row">
        <div class="col-xs-12">
          <%= f.text_field :name, :class => 'input-shaptar', :placeholder => 'Nombre y Apellido' %>
        </div>
        <div class="col-xs-12">
          <%= f.number_field :telephone, :class => 'input-shaptar', :placeholder => 'Teléfono' %>
        </div>
        <div class="col-xs-12">
          <%= f.email_field :email, :class => 'input-shaptar', :placeholder => 'Correo Electrónico' %>
        </div>
        <div class="col-xs-12">
          <%= f.submit 'Enviar Mensaje', :class => 'button-shaptar-green' %>
        </div>
      </div>
    </div>

  </div>

<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Mensajes</h1>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Teléfono</th>
      <th>Correo Electrónico</th>
      <th>Fecha de Recibido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.telephone %></td>
        <td><%= contact.email %></td>
        <td><%= contact.created_at %></td>
        <td class="text-end"><%= link_to 'Ver Correo', contact %> | <%= link_to 'Eliminar', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p>
  <strong>Fecha de Recibido:</strong>
  <%= @contact.created_at %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Teléfono:</strong>
  <%= @contact.telephone %>
</p>

<p>
  <strong>Correo Electrónico:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Mensaje:</strong><br>
  <%= @contact.message %>
</p>

<%= link_to 'Atras', contacts_path %>